# Task1 做习题

In [1]:
# 1
import numpy as np

In [2]:
#2
print(np.__version__)

1.16.2


In [4]:
#3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
#4
x = np.eye(10)
print("%d bytes" %(x.size*x.itemsize))

800 bytes


In [10]:
#5 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [16]:
#6
y = np.random.random(10)
y[4] = 1
print(y)

[0.46258177 0.84617449 0.91415222 0.36793977 1.         0.52306917
 0.21751645 0.64462523 0.77817028 0.09508355]


In [17]:
#7
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [18]:
#8
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [19]:
#9
t = np.arange(9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [22]:
#10
t = np.array([1,2,3,0,0,7,9])
print(np.nonzero(t))


(array([0, 1, 2, 5, 6], dtype=int64),)


In [23]:
#11
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#12
np.random.random((3,3,3))

array([[[0.45371541, 0.12522553, 0.56248207],
        [0.48396249, 0.80891062, 0.33167663],
        [0.23891579, 0.20522556, 0.75592564]],

       [[0.95694062, 0.78401042, 0.53158192],
        [0.38858853, 0.20034582, 0.17641489],
        [0.59444643, 0.18171865, 0.07386374]],

       [[0.6673288 , 0.51397618, 0.50859729],
        [0.86501753, 0.73438887, 0.319773  ],
        [0.91953432, 0.15139501, 0.02457987]]])

In [27]:
#13
z = np.random.random((10,10))
print(z.min(),z.max())
print(z.argmin(),z.argmax())

0.0011876946547765277 0.9888791538656079
48 3


In [28]:
#14
z = np.random.random(30)
print(z.mean())

0.5620917257205919


In [34]:
#15
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [35]:
#16
z = np.ones((10,10))
z = np.pad(z,pad_width=1,mode='constant')
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [36]:
#17
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [39]:
#18
z = np.diag(np.arange(4),k=-1) + 1
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]


In [42]:
#19
z = np.zeros((8,8))
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [43]:
#20
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [46]:
#21
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [47]:
#22
z = np.random.random((5,5))
print(z)
print('-------------')
z = (z-z.min()) / (z.max() - z.min())
print(z)

[[0.14519253 0.78875932 0.95450814 0.98994808 0.6352648 ]
 [0.95419331 0.34290076 0.03075569 0.2892851  0.26230092]
 [0.188604   0.93624432 0.21935232 0.38217647 0.33779441]
 [0.43204661 0.4703501  0.27261393 0.23728653 0.80931835]
 [0.66503998 0.18161159 0.81643708 0.51112044 0.46545563]]
-------------
[[0.11930541 0.79025192 0.96305231 1.         0.63022718]
 [0.96272409 0.32542488 0.         0.26952821 0.24139602]
 [0.16456377 0.94401148 0.19662023 0.36637153 0.32010128]
 [0.41836333 0.45829639 0.25214778 0.21531743 0.81168561]
 [0.66126909 0.15727387 0.81910719 0.50080125 0.45319369]]


In [48]:
#23
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [49]:
#24
x = np.random.random((5,3))
y = np.random.random((3,2))
x.dot(y)

array([[0.47996594, 0.41756827],
       [0.77151075, 0.70893753],
       [0.45742591, 0.4160843 ],
       [0.93636681, 0.81948405],
       [1.02060144, 0.96316095]])

In [54]:
#25
z = np.arange(10)
z[(3<z)&(z<=8)] *=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [55]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [ ]:
#27
