# Task1 做习题

In [2]:
# 1
import numpy as np

In [3]:
#2
print(np.__version__)

1.16.2


In [4]:
#3
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
#4
x = np.eye(10)
print("%d bytes" %(x.size*x.itemsize))

800 bytes


In [6]:
#5 
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [7]:
#6
y = np.random.random(10)
y[4] = 1
print(y)

[0.03443252 0.180315   0.96881846 0.25723743 1.         0.33703396
 0.32651005 0.16070351 0.10096538 0.2089848 ]


In [8]:
#7
z = np.arange(10,50)
print(z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [9]:
#8
print(z[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [10]:
#9
t = np.arange(9).reshape(3,3)
print(t)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [11]:
#10
t = np.array([1,2,3,0,0,7,9])
print(np.nonzero(t))


(array([0, 1, 2, 5, 6], dtype=int64),)


In [12]:
#11
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
#12
np.random.random((3,3,3))

array([[[0.24260066, 0.83158328, 0.41734524],
        [0.11205212, 0.01453125, 0.415004  ],
        [0.39247357, 0.3643359 , 0.17738681]],

       [[0.82424464, 0.36327647, 0.003028  ],
        [0.6311796 , 0.41437425, 0.46757229],
        [0.29595918, 0.5356632 , 0.35502138]],

       [[0.48480405, 0.25329547, 0.12897181],
        [0.55090669, 0.99316294, 0.46076696],
        [0.82055739, 0.41668295, 0.00893346]]])

In [14]:
#13
z = np.random.random((10,10))
print(z.min(),z.max())
print(z.argmin(),z.argmax())

0.013295874436804467 0.997920216698878
41 56


In [15]:
#14
z = np.random.random(30)
print(z.mean())

0.5432354516656712


In [16]:
#15
z = np.ones((10,10))
z[1:-1,1:-1] = 0
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [17]:
#16
z = np.ones((10,10))
z = np.pad(z,pad_width=1,mode='constant')
print(z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [18]:
#17
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan-np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


In [19]:
#18
z = np.diag(np.arange(4),k=-1) + 1
print(z)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 2 1 1 1]
 [1 1 3 1 1]
 [1 1 1 4 1]]


In [20]:
#19
z = np.zeros((8,8))
z[1::2,::2] = 1
z[::2,1::2] = 1
print(z)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


In [21]:
#20
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [22]:
#21
z = np.tile(np.array([[0,1],[1,0]]),(4,4))
print(z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [23]:
#22
z = np.random.random((5,5))
print(z)
print('-------------')
z = (z-z.min()) / (z.max() - z.min())
print(z)

[[0.81411695 0.68638145 0.97865261 0.95242702 0.72244575]
 [0.65191302 0.5443394  0.70346384 0.21472938 0.2565266 ]
 [0.57718303 0.70327278 0.88822333 0.90619539 0.63954442]
 [0.16662333 0.09454505 0.17625527 0.55421027 0.95259496]
 [0.67183755 0.44899    0.59541595 0.12212435 0.71828533]]
-------------
[[0.81389633 0.66941674 1.         0.97033665 0.7102085 ]
 [0.63043004 0.50875523 0.68873836 0.13593858 0.18321475]
 [0.54590415 0.68852225 0.89771688 0.91804479 0.61644012]
 [0.08152659 0.         0.09242113 0.51992002 0.9705266 ]
 [0.65296636 0.40090704 0.5665271  0.0311945  0.70550271]]


In [24]:
#23
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

In [25]:
#24
x = np.random.random((5,3))
y = np.random.random((3,2))
x.dot(y)

array([[0.73116129, 1.43377838],
       [0.58254898, 0.88882612],
       [0.83552702, 1.39731502],
       [0.9127725 , 1.52537025],
       [0.92922768, 1.64588355]])

In [26]:
#25
z = np.arange(10)
z[(3<z)&(z<=8)] *=-1
print(z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9]


In [27]:
#26
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [40]:
#27
z = np.arange(6)
print(z)
print(z**z)
print(2<<z>>2)
print(z<-z)
print(z/1/1)
#print(z<z>z) #false

[0 1 2 3 4 5]
[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0. 1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [44]:
#28
print(np.arange(0)/np.arange(0))
print(np.arange(0)//np.arange(0))
print(np.array([np.nan]).astype(int).astype(float))

array([-2.14748365e+09])

In [47]:
#29
z = np.random.uniform(-10,+10,10)
print(z)
print(np.ceil(np.abs(z)))
print(np.copysign(np.ceil(np.abs(z)),z))

[-3.84308606  1.202645    5.22484198  5.80528575  8.3932483  -4.58456567
  7.71265136 -0.19510567  4.50895592  4.6057511 ]
[4. 2. 6. 6. 9. 5. 8. 1. 5. 5.]
[-4.  2.  6.  6.  9. -5.  8. -1.  5.  5.]


In [54]:
#30
z1 = np.random.randint(0,10,10)
z2 = np.random.randint(0,10,10)
print(z1)
print(z2)
print(np.intersect1d(z1,z2))
print((set(z1)&set(z2)))

[2 9 3 4 0 6 5 2 6 0]
[7 4 1 0 3 7 7 0 3 9]
[0 3 4 9]
{0, 9, 3, 4}


In [55]:
#31
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)


In [56]:
#32
np.sqrt(-1) == np.emath.sqrt(-1)

C:\Users\Zelon\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

In [ ]:
#33
